version: "3"

services:
  client:
    build:
      context: ../..
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "5000:80"
  server:
    build:
      context: ../..
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "5001:3001"
    volumes:
      - ../../server:/server
      - /server/node_modules
    restart: always
